
/**
 * board
 */

export const CHANGE_CELL_TYPE = 'CHANGE_CELL_TYPE';
export const CLEAR_HIGHLIGHT_CELLS = 'CLEAR_HIGHLIGHT_CELLS';
export const ADD_HIGHLIGHT_CELLS = 'ADD_HIGHLIGHT_CELLS';
export const TOGGLE_CURRENT_PLAYER = 'TOGGLE_CURRENT_PLAYER';
export const CHANGE_BOARD_SIZE = 'CHANGE_BOARD_SIZE';
export const RESET_BOARD = 'RESET_BOARD';
export const MOVE = 'MOVE'
